#This Vagrant file will create ubuntu machine and install nginx and copy an HTML file to html directory


Vagrant.configure("2") do |config|


  ### Nginx VM ###
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/bionic64"
      web01.vm.hostname = "web01"
      web01.vm.network "forwarded_port", guest: 80, host: 8080
      web01.vm.network "private_network", ip: "192.168.56.10"
      web01.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = true
        vmware.allowlist_verified = true
      end
      #web01.privileged = true
      web01.vm.provision "shell", inline:<<-SHELL
      apt-get update -y
      apt-get upgrade -y
      apt-get install -y nginx
      SHELL
      web01.vm.provision "file", 
      source:"sample.html",
      destination: "/tmp/index.nginx-debian.html"
      web01.vm.provision "shell",
          inline: "mv /tmp/index.nginx-debian.html /var/www/html/index.nginx-debian.html"
    end
  end